from .accountSerializer import PerfilSerializer
from .userSerializer import UserSerializer
from .ciudadSerializer import CiudadSerializer
from .pacienteSerializer import PacienteSerializer
from .his_clinicaSerializer import HistoriaClinicaSerializer
from .per_saludSerializer import PersonalSaludSerializer
from .sig_vitalesSerializer import SignosVitalesSerializer
from .familiarserializer import FamiliarSerializer