# Generated by Django 4.1.1 on 2022-09-20 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ciudad', models.CharField(max_length=15, unique=True, verbose_name='ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_nacimiento', models.DateField(max_length=30, verbose_name='Fecha_nacimiento')),
                ('direccion', models.CharField(max_length=100, verbose_name='Direccion')),
                ('id_ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to='AppHospital52.ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id_perfil', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.IntegerField()),
                ('username', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=256, verbose_name='Password')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=30, verbose_name='Apellido')),
                ('telefono', models.CharField(max_length=30, verbose_name='Telefono')),
                ('genero', models.CharField(max_length=30, verbose_name='Genero')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('id_perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='AppHospital52.perfil')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SignosVitales',
            fields=[
                ('id_signos', models.AutoField(primary_key=True, serialize=False)),
                ('oximetria', models.CharField(max_length=30, verbose_name='Oximetria')),
                ('frecuenciaRes', models.CharField(max_length=30, verbose_name='FrecuenciaRes')),
                ('frecuenciaCar', models.CharField(max_length=30, verbose_name='FrecuenciaCar')),
                ('temperatura', models.CharField(max_length=30, verbose_name='Temperatura')),
                ('glisemia', models.CharField(max_length=30, verbose_name='Glisemia')),
                ('presionArt', models.CharField(max_length=30, verbose_name='PresionArt')),
                ('fechahora', models.DateTimeField(max_length=30, verbose_name='Fechahora')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sig_vitales', to='AppHospital52.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalSalud',
            fields=[
                ('id_per_salud', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(max_length=30, verbose_name='Rol')),
                ('especialidad', models.CharField(max_length=30, verbose_name='Especialidad')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='per_salud', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='id_per_salud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to='AppHospital52.personalsalud'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id_historiaclinica', models.AutoField(primary_key=True, serialize=False)),
                ('sugenrencias', models.CharField(max_length=250, verbose_name='Sugenrencias')),
                ('diagnostico', models.CharField(max_length=250, verbose_name='Diagnostico')),
                ('entorno', models.CharField(max_length=250, verbose_name='Entorno')),
                ('fechasugerencias', models.DateField(max_length=250, verbose_name='Fechasugerencias')),
                ('descripcion', models.CharField(max_length=250, verbose_name='Descripcion')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='his_clinica', to='AppHospital52.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id_familiar', models.AutoField(primary_key=True, serialize=False)),
                ('parentesco', models.CharField(max_length=30, verbose_name='Parentesco')),
                ('correo', models.EmailField(max_length=100, verbose_name='Correo')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familiar', to='AppHospital52.paciente')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familiar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
