from .userCreateView import UserCreateView
from .userDetailView import UserDetailView
from .pacienteView import GestionPaciente
from .ciudadDetailView import GestionCiudad
from .ciudadDetailViewId import GestionCiudadId
from .familiarView import GestionFamiliar
from .per_saludView import GestionPerSalud
from .his_clinicaView import GestionHisClinica
from .accountView import GestionPerfil