from .userCreateView import UserCreateView
from .userDetailView import UserDetailView
from .pacienteView import GestionPaciente
from .pacienteView import GestionDetailPaciente
from .ciudadDetailView import GestionCiudad
from .ciudadDetailView import GestionDetailCiudad
from .per_saludView import GestionPerSalud
from .per_saludView import GestionDetailPersonalSalud
from .his_clinicaView import GestionHisClinica
from .his_clinicaView import GestionDetailHisClinica
from .accountView import GestionPerfil
from .accountView import GestionDetailPerfil
from .sig_vitalesView import GestionSignosVitales
from .sig_vitalesView import GestionDetailSignosVitales
from .familiarView import GestionFamiliar
